apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"aqua-cloud-connector"},"name":"aqua-cloud-connector","namespace":"aqua"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"aqua-cloud-connector"}},"template":{"metadata":{"labels":{"app":"aqua-cloud-connector"},"name":"aqua-cloud-connector","namespace":"aqua"},"spec":{"containers":[{"env":[{"name":"AQUA_SERVER","value":"3568b95554-gw.cloud.aquasec.com:443"},{"name":"AQUA_CLOUD_CONNECTOR_CONFIG_FILE_PATH","value":"/etc/config/connector.yaml"},{"name":"AQUA_CLOUD_CONNECTOR_USERNAME","valueFrom":{"secretKeyRef":{"key":"username","name":"user-secret"}}},{"name":"AQUA_CLOUD_CONNECTOR_TOKEN","valueFrom":{"secretKeyRef":{"key":"token","name":"user-secret"}}},{"name":"AQUA_CLOUD_CONNECTOR_HEALTH_PORT","value":""},{"name":"AQUA_TLS_VERIFY","value":"1"}],"image":"registry.aquasec.com/aqua-cloud-connector:2022.4","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":8080}},"name":"aqua-cloud-connector","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/config","name":"config"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"aqua-registry"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":11433,"runAsGroup":11433,"runAsUser":11431},"serviceAccount":"aqua-sa","serviceAccountName":"aqua-sa","terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"items":[{"key":"aqua-cloud-connector-config","path":"connector.yaml"}],"name":"aqua-cloud-connector-conf"},"name":"config"}]}}}}
  creationTimestamp: "2024-07-05T03:46:48Z"
  generation: 4
  labels:
    app: aqua-cloud-connector
  name: aqua-cloud-connector
  namespace: aqua
  resourceVersion: "963961388"
  uid: 4fa47727-060b-4f56-a1a0-4bb61e4a537f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aqua-cloud-connector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aqua-cloud-connector
      name: aqua-cloud-connector
      namespace: aqua
    spec:
      containers:
      - env:
        - name: AQUA_SERVER
          value: 3568b95554-gw.cloud.aquasec.com:443
        - name: AQUA_CLOUD_CONNECTOR_CONFIG_FILE_PATH
          value: /etc/config/connector.yaml
        - name: AQUA_CLOUD_CONNECTOR_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: user-secret
        - name: AQUA_CLOUD_CONNECTOR_HEALTH_PORT
        - name: AQUA_TLS_VERIFY
          value: "1"
        image: registry.aquasec.com/aqua-cloud-connector:2022.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: aqua-cloud-connector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aqua-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 11433
        runAsGroup: 11433
        runAsUser: 11431
      serviceAccount: aqua-sa
      serviceAccountName: aqua-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: aqua-cloud-connector-config
            path: connector.yaml
          name: aqua-cloud-connector-conf
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-05T03:46:48Z"
    lastUpdateTime: "2024-07-05T03:52:11Z"
    message: ReplicaSet "aqua-cloud-connector-876fc5bd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-07-05T09:35:44Z"
    lastUpdateTime: "2024-07-05T09:35:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
