apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: poc-
commonLabels:
  env: poc

bases:
  - ../../base

#resources:
#  - repository.yaml

patchesStrategicMerge:
  - application.yaml
