apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${SYSTEM_NAME}-${SERVICE_NAME}
  namespace: openshift-gitops
  # Add this finalizer ONLY if you want these to cascade delete.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
