apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ../../base




#namePrefix: dev-
#commonLabels:
#  env: dev

patches:
#  - path: deployment.yaml
- path: ingress.yaml
