apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config-version: "1"
  name: configure-service-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: "configure-service"      
        image: 908027398801.dkr.ecr.ap-southeast-1.amazonaws.com/poc-dev/configureservice:f147437-2024-10-28-02-01



