apiVersion: apps/v1
kind: Deployment
metadata:
  name: configure-service-deployment
spec:
  selector:
    matchLabels:
      app: "configure-service"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "configure-service"
    spec:
      containers:
      - name: "configure-service"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP

