apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
data:
  ASPNETCORE_ENVIRONMENT: Development
  ApiSettings__FinancialServiceBaseUrl: "http://financial-service/api"
  ApiSettings__ConfigureServiceBaseUrl: "http://configure_service"