apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
- ../../base
- namespace.yaml

#namePrefix:
#- path: metadata/name
#- path: kind/spec/name

#namePrefix: 
#  qa-

