apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: "2048"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

