apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: "user-service"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "user-service"
    spec:
      containers:
      - name: "user-service"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP

