apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: demo-service 
spec:
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "2048"
  type: NodePort
