apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
- ../../base
#- namespace.yaml
- nginx-cm-v1.yaml
- nginx-cm-v2.yaml

#namePrefix: dev-
#commonLabels:
#  env: dev
